server:
  port: 9091
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/jwt_login_app?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  #JPA Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  #Simple mail service
  mail:
    host: smtp.gmail.com
    port: 587
    username: amitchavda9879@gmail.com
    password: qwduprkoudduskrz
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true